# The configuration file for docking actions that robots can perform
# FleetName: The name of the fleet
# DockName: The name of the docking waypoint
# level_name: The level name
# path: The waypoints that the robot will pass through during the docking process)
# finish_waypoint: The name of the waypoint where the robot will end up at the end of the docking process
#
# Note: These waypoints are in (x meters, y meters, yaw radian) form
#
# If loaded correctly, you will be able to echo the msg via:
# ros2 topic echo /dock_summary --qos-durability transient_local --qos-reliabilityreliable

# Configuring Cleaning path:
# The full cleaning path which the robot will travel along. When configuring, the first
# waypoint is required to be the current robot's waypoint.
cleanerBotA:
  clean_RCI:
    level_name: "L1"
    path: [ [7.2234, -7.8462, 0.0],
            [8.9048, -7.8462, 0.0],
            [8.9048, -9.5524, 0.0],
            [8.9048, -11.2711, 0.0],
            [5.7912, -11.2711, 0.0],
            [5.7912, -9.5524, 0.0],
          ]
    finish_waypoint: "clean_RCI"